### ISSUE TITLE
mageia i586 many attempts keep failing to boot iso

### ISSUE THREAD

**Issue by 0nlyHuman** [unity-linux/mklivecd#6]
32 bit i586 mageia seems to fail at initrd make-boot-splash-raw tried adding option --nosplash it created iso gets a boot splash but fails after reaching ramdisk, then says,  /bin/probe-modules: error while loading shared libraries: libz.so.1 cannot open shared object file: No such file or Directory
Wondering if missing something, but no idea what.
(Did not see any unitylinux i586 iso's to try)
Ps. I did some time ago modify an old unity iso, x86_64 one that had a graphical boot screen, from September 23, 2017 I installed some mageia stuff for compatibility, I later made another iso from it and added enlightenment :)

**Comment by jmiahman** [comment]
looks like libz is missing, can you upload the image some where so I can further trouble-shoot? I haven't tested much in 32bit

**Comment by 0nlyHuman** [comment]
I first used a mageia xfce livedvd, gave up on that so then downloaded the mageia 6 i586 netinstaller iso and built it up which I still have installed, far as I can see they both had libz an its devel rpm installed,  could it be a mageia i586 problem?

**Comment by jmiahman** [comment]
Okay the initrd that loads zlib is handled by dracut, an upstream project I do not control or patch, that every distro uses. The recent versions of mklivecd call dracut the exact same way Fedora, Mageia, Ubuntu and others do. Unless you offer me an image to look at I can't duplicate this in i586 or x86_64, boots fine here. If you're using an older version, then it's broke and will no longer function (why we switched to dracut in the first place), most likely due to upstream changes with Mageia that were over due. I noticed you didn't give a version or detailed information outside of the lib not being loaded on boot. Since I can't duplicate that with current versions then I can't fix it. So I need the image you are having issues with (the generated image having issues) and the version of mklivecd you are using, if not current. Otherwise there's nothing I can do.

**Comment by 0nlyHuman** [comment]
Fair enough, do you have a link to a i586 iso that remasters and boots to desktop, preferably one not too large? I can give you an iso that has the problem. I will look for it an upload. Thanks, uploading it just has mklivecd on it no unity repo added, hope not something stupid on my part.

**Comment by 0nlyHuman** [comment]
Well I updated to latest mklivecd and dracut creates initrd :) though then fails as it is looking for /boot/grub/themes   themes are in grub2  I will tried copying grub2 themes to grub, it now seems to be working, though wondering if I should have deleted grub an copied grub2 renaming it to grub., will see if iso boots when created, thanks.
**Update:**  created iso boot screen was black with 2 lines of text, so no theme but it booted, thanks :)
screenshot: https://www.enlightenment.org/ss/e-5a7867ad8aac22.63758071.jpg

**Comment by jmiahman** [comment]
No there's code that needs to be changed for thew rpm version you're running to look in the proper place..
